Adding a approving leave guide for management
publiccodenet/about pull request #1128
Opened 2022-02-21 09:52 UTC by bvhme

Reflect approving leave as a process and update the leave guide to be in line with it.

-----
[View rendered activities/staff-information/leave.md](https://github.com/publiccodenet/about/blob/leave-management/activities/staff-information/leave.md)
[View rendered activities/staff-management/approving-leave.md](https://github.com/publiccodenet/about/blob/leave-management/activities/staff-management/approving-leave.md)

2022-02-21 09:54 UTC, clausmullie commented on activities/staff-management/approving-leave.md
> +A leave request email is submitted through the personal Tentoo account of the employee or through email if employed outside of the Netherlands. in line with the [staff leave guide](../staff-informati
```suggestion
A leave request email is submitted through the personal Tentoo account of the employee or through email if employed outside of the Netherlands, in line with the [staff leave guide](../staff-information/leave.md).
```

2022-02-21 09:55 UTC, clausmullie commented on activities/staff-management/approving-leave.md
> +1. See the leave overview in Tentoo NMBRS to see if their leave overlaps with their colleagues and if necessary ask if they have discussed with their planning with their team.
```suggestion
1. Check the leave overview in Tentoo NMBRS to see if their leave overlaps with their colleagues, and if necessary ask if they have discussed their planning with their team.
```

2022-02-21 09:57 UTC, clausmullie commented on activities/staff-management/approving-leave.md
> +2. Check the balance of leave in the leave overview. If this balance is low offer for them to buy their leave.
```suggestion
2. Check the balance of leave in the leave overview. If this balance is low, remind them of the possibility to buy extra leave.
```

2022-02-21 14:42 UTC, clausmullie requested changes
Some in-line suggestions above

2022-02-28 08:11 UTC, ericherman requested changes
Please commit the suggested commas from Claus

2022-03-09 14:37 UTC, ericherman approved these changes

2022-03-09 14:42 UTC, Ainali approved these changes

2022-03-09 15:31 UTC, clausmullie approved these changes

2022-03-09 15:33 UTC, merged