Ops handbook finance management
publiccodenet/about pull request #833
Opened 2021-01-11 15:44 UTC by demkodo

Big PR and chances of an unhappy Travis - let' see :)

2021-01-12 20:55 UTC, ElenaFdR commented on activities/finance-management/bookkeeping.md
> +[GetMonkeys](https://getmonkeys.io/) is our service provider. They process and book all the payments every second Wednesday of the month. Any corrections can be mailed to the bookkeeper and are proce
```suggestion
[GetMonkeys](https://getmonkeys.io/) is our service provider. They process and book all the payments every second Wednesday of the month. Any corrections can be mailed to the bookkeeper and are processed the next day. GetMonkeys is also responsible for producing our annual financial reports and can be asked for other financial services based on our needs.
```

2021-01-12 20:55 UTC, ElenaFdR commented on activities/finance-management/bookkeeping.md
> +[Exact is a Dutch software company](https://www.exact.com/) that offers accounting, ERP, and other software for small and medium enterprises. We have a license via GetMonkey’s. The Operations Coordin
```suggestion
[Exact is a Dutch software company](https://www.exact.com/) that offers accounting, ERP, and other software for small and medium enterprises. We have a license via GetMonkeys. The Operations Coordinator and Chief Executive have access to Exact. Temporary access can be given to financial consultants.
```

2021-01-13 10:33 UTC, lscheske commented on activities/finance-management/reporting.md
> +Annual reporting consists of the annual financial statement and an annual report. The latter is a powerful piece of communications that shows how we deliver on our mission, and celebrate our accompli
```suggestion
As an ANBI, we are legally obliged to publish two kinds of reports: an annual financial statement (Jaarrekening, see below) and an annual report (Jaarverslag). The latter is a powerful piece of communications that shows how we deliver on our mission, achieve the goals set out in our policy plan, and celebrate our accomplishments.
```

2021-01-13 10:34 UTC, lscheske commented on activities/finance-management/reporting.md
> +## Financial annual statement
```suggestion
## Annual financial statement
```

2021-01-13 10:36 UTC, lscheske commented on activities/finance-management/reporting.md
> +Our first financial year runs from 1 July 2019 - 31 December 2020. The Operations Coordinator is working closely with the bookkeeper to produce the statement. An ANBI has to publish the financial sta
```suggestion
The Operations Coordinator is responsible for producing the annual financial statement (Jaarverslag), in close collaboration with our bookkeeper. The financial statement should include the following information:
```

2021-01-13 10:36 UTC, lscheske commented on activities/finance-management/reporting.md
> +The financial statement must be published on our website within 6 six months after the end of the financial year.
```suggestion
The financial statement must be published on our website within six months after the end of the financial year.
```

2021-01-13 10:38 UTC, lscheske commented on activities/finance-management/reporting.md
> +The King Baudouin Foundation’s mission is to contribute to a better society. The Foundation is an actor for change and innovation, serving the public interest and increasing social cohesion in Belgiu
```suggestion
```

2021-01-13 10:40 UTC, lscheske commented on activities/finance-management/reporting.md
> +The King Baudouin Foundation’s mission is to contribute to a better society. The Foundation is an actor for change and innovation, serving the public interest and increasing social cohesion in Belgiu
No need to include this information about them - this section is about reporting and what we need to deliver based on our legal agreements with them. Providing the link to the drive with all the background info should be sufficient.

2021-01-13 10:42 UTC, lscheske reviewed
I've made a couple of editorial suggestions throughout.

File #11 is the same as PR #831 and also duplicates a change made in PR #832

2021-02-18 10:53 UTC, lscheske commented on activities/finance-management/bookkeeping.md
> +* We have ANBI status: read more information about ANBI benefits and requirements
Link is missing to the "Read more information about ANBI benefits and requirements"

2021-02-18 10:55 UTC, lscheske reviewed
Just some minor changes, then this is good to go.

2021-02-25 15:13 UTC, ElenaFdR commented on activities/finance-management/authorization.md
> +Board members – two board members can decide on payments above € 50.000. [See bylaws.](../../organization/articles-of-association.md)
```suggestion
Two board members can approve payments above € 50.000. [See bylaws.](../../organization/articles-of-association.md)
```

2021-02-25 15:14 UTC, ElenaFdR commented on activities/finance-management/authorization.md
> +Board members – two board members can decide on payments above € 50.000. [See bylaws.](../../organization/articles-of-association.md)
In American/British English, you don't usually put a space between a currency symbol and currency amount.

2021-02-25 15:15 UTC, ElenaFdR commented on activities/finance-management/bank.md
> +Our bank is the Rabobank. There is a checking and savings account. We are in progress of opening a USD account. There are bank cards and credit cards and online keys. Bank cards:
```suggestion
Our bank is the Rabobank. There is a EUR checking and savings account. We are in progress of opening a USD account. There are bank cards and credit cards and online keys. Bank cards:
```

2021-03-11 13:10 UTC, ElenaFdR requested changes
Very clear and complete explanation of our financial administration!
Some small proofreading suggestions, but otherwise very close to being ready to go.

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +
Suggestion: add an intro sentence for context.

```suggestion

We produce financial reports for different audiences throughout the year.
```
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +The Operations Coordinator is responsible for producing the annual financial statement (Jaarverslag), in close collaboration with our bookkeeper. The financial statement should include the following
Are the contents of the jaarverslag optional?
```suggestion
The Operations Coordinator is responsible for producing the annual financial statement (jaarverslag), in close collaboration with our bookkeeper. The financial statement must include the following information:
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +[Template for our annual financial statement.](https://drive.google.com/drive/folders/1eeW-cCescwdGoxuCKwB4oMlhE5512Qu_)
```suggestion
[Template for our annual financial statement](https://drive.google.com/drive/folders/1eeW-cCescwdGoxuCKwB4oMlhE5512Qu_).
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +We opened a fund at the KBFUS Foundation to enable smooth faciliation of receiving gifts from US donors. The name of our fund is [“Foundation for Public Code US Fund”.](https://kbfus.networkforgood.c
Is the word 'foundation' redundant in 'KBFUS Foundation'?

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +We opened a fund at the KBFUS Foundation to enable smooth faciliation of receiving gifts from US donors. The name of our fund is [“Foundation for Public Code US Fund”.](https://kbfus.networkforgood.c
```suggestion
We opened a fund at the KBFUS Foundation to facilite receiving gifts from US donors. The name of our fund is [“Foundation for Public Code US Fund”](https://kbfus.networkforgood.com/projects/52915-p-kbfus-funds-foundation-for-public-code-nl).
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +The Operations Coordinator has log-in credentials to the grants interface where the fund is managed and reports can be filed. [More information about the fund and how the process works can be found o
```suggestion
The Operations Coordinator has log-in credentials to the grants interface where the fund is managed and reports can be filed. [More information about the fund and how the process works](https://drive.google.com/drive/folders/1hv1XKbA6y8XYO9KqbKo5-TFlFxRROn0R) can be found on the Drive.
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +The Foundation for Public Code needs to provide a narrative and financial report on the use of grant funds to KBFUS no less than annually and final reports upon completion of the grant period and unt
```suggestion
The Foundation for Public Code needs to provide a narrative and financial report on the use of grant funds to KBFUS no less than annually and final reports upon completion of the grant period and until grant funds are expended in full. The reports should include a narrative account of how grant funds were used, what was accomplished by the expenditure of funds (including a description of progress made towards achieving the goals of the grant), and compliance with the terms of the Agreement, along with a financial statement and copies of any publications resulting from the grant.
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +The Foundation for Public Code needs to provide a narrative and financial report on the use of grant funds to KBFUS no less than annually and final reports upon completion of the grant period and unt
Does our agreement with them have any other description than 'Agreement'?

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/reporting.md
> +The report should be signed by an authorized officer, and the financial statement should be attested by the responsible financial officer or a certified public accountant, and should reflect the cate
```suggestion
The report should be signed by an authorized officer, and the financial statement should be attested by the responsible financial officer or a certified public accountant, and should reflect the categories stipulated in the attached approved budget. The report must include a reconciliation of all amounts spent for the purpose specified, with the total grant proceeds received. [Detailed financial requirements can be found on our Drive](https://drive.google.com/drive/folders/1Tv5j1vfn2MhDc2DtDmKCyQrrfkh2CJTj).
```

2021-03-11 13:10 UTC, ElenaFdR commented on activities/finance-management/authorization.md
> +Two board members can approve payments above € 50.000. [See bylaws.](../../organization/articles-of-association.md)
Suggest changing all periods in numbers in the thousands to commas, as is more common in English.

2021-03-11 16:14 UTC, ElenaFdR submitted a review, later dismissed
Amazing work!

2021-03-11 16:15 UTC, ElenaFdR commented on activities/finance-management/index.md
> +* [Authorization](authorization.md)
```suggestion
* [Financial authorization](authorization.md)
```

2021-03-11 16:15 UTC, ElenaFdR approved these changes

2021-03-15 09:58 UTC, clausmullie commented
In the interest of iterative working, I'm going to merge this. Awesome stuff! :+1:

2021-03-15 09:58 UTC, merged