Update prepare-livestream.md
publiccodenet/about pull request #848
Opened 2021-01-28 12:37 UTC by AlbaRoza

Added a few details to the 'Communication' section.

2021-01-28 12:39 UTC, Ainali commented
This is a good addition of details, thanks!

2021-01-28 12:41 UTC, Ainali commented on activities/live-streaming/prepare-live-stream.md
> +- Text messages for social media. Use Planable for the scheduling of those.
When this ends with a full stop, should all bullet points have full stop? I am unsure. Thoughts @ElenaFdR

2021-06-03 07:11 UTC, Ainali requested changes

2021-06-03 07:11 UTC, Ainali commented on activities/live-streaming/prepare-live-stream.md
> +- Text messages for social media. Use Planable for the scheduling of those.
```suggestion
- Text messages for social media. Use Planable for the scheduling of those
```

2021-06-07 06:11 UTC, AlbaRoza reviewed
Nice add!

2021-06-07 09:54 UTC, Ainali approved these changes

2021-06-08 06:54 UTC, merged