Update newsletter and community call sign up to use Odoo survey
publiccodenet/about pull request #890
Opened 2021-03-16 12:56 UTC by Ainali

Exchange Google forms to the Odoo survey and added instructions
on how to use the survey for community call and newsletter sign up.

Addresses #813

2021-03-16 13:04 UTC, demkodo commented on activities/communication/sign-up.md
> +We use [Odoo](../tool-management/odoo.md) to manage the sign up process. The modules that we use are Surveys and Contacts. In Odoo we have one survey called *Newsletter and community calls*, which is
I'd remove "that" after "the modules". I'd replace "one survey

2021-03-16 13:10 UTC, ElenaFdR commented on activities/communication/sign-up.md
> +We use [Odoo](../tool-management/odoo.md) to manage the sign up process. The modules that we use are Surveys and Contacts. In Odoo we have one survey called *Newsletter and community calls*, which is
```suggestion
We use [Odoo](../tool-management/odoo.md) to manage the sign up process. The modules we use are Surveys and Contacts. In Odoo we have a survey called *Newsletter and community calls*, which configures the [sign up form](https://odoo.publiccode.net/survey/start/594b9243-c7e5-4bc1-8714-35137c971842).
```

2021-03-16 13:12 UTC, ElenaFdR commented on activities/communication/sign-up.md
> +When preparing for sending out [invites to community calls](../standard-maintenance/preparing-community-call.md) or the newsletter, first the contacts need to be updated. Check in the notes in the bo
```suggestion
When preparing to send out [invitations to community calls](../standard-maintenance/preparing-community-call.md) or the newsletter, first the contacts need to be updated. Check in the notes in the bottom of the survey when it was last updated. In the top right corner of the survey there is a button stating how many answers the survey has. Clicking it reveals all the persons that have signed up and their options. By selecting all the answers that were `Created on` later than when it was last updated and then the download button in the top left corner you get all the answers in one file. With the details from the file, update existing contacts or create new ones. Use the tags ´Newsletter´, ´Community Call / Foundation', ´Community Call /Standard´ and ´SendValuable´ to store their preferences for being contacted.
```

2021-03-16 13:12 UTC, demkodo commented on activities/staff-meetings/event-debrief.md
>      * who are the interesting people we met?
we've met

2021-03-16 13:13 UTC, ElenaFdR requested changes
Small changes, then ready to go! Are you also updating the universal footer on the Jekyll theme?

2021-03-16 13:17 UTC, ElenaFdR commented
Sorry, I've just spotted that that's already covered in the issue.

2021-03-16 13:44 UTC, demkodo commented on activities/communication/sign-up.md
> +We use [Odoo](../tool-management/odoo.md) to manage the sign up process. The modules that we use are Surveys and Contacts. In Odoo we have one survey called *Newsletter and community calls*, which is
```suggestion
We use [Odoo](../tool-management/odoo.md) to manage the sign up process. The modules that we use are Surveys and Contacts. In Odoo we have one survey called *Newsletter and community calls*, which is the one that configures the [sign up form](https://odoo.publiccode.net/survey/start/594b9243-c7e5-4bc1-8714-35137c971842).
```

2021-03-18 10:29 UTC, ElenaFdR approved these changes
This is good to go! An idea for a future iteration: add info somewhere that this approach keeps us GDPR compliant because we have a record showing that we have someone's contact details by their consent (#350).

2021-03-18 10:31 UTC, merged